# Build phase
FROM node:18.6.0-alpine3.15 AS build

WORKDIR /usr/src/app

COPY package.json .
COPY pnpm-lock.yaml .

RUN yarn global add pnpm
RUN pnpm install

COPY . .

CMD ["pnpm", "build"]

# Serve phase
FROM nginx:stable-alpine

COPY ./config/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build/ /srv